/*
Solar API

Testing WorkspaceSourceApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_client_WorkspaceSourceApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test WorkspaceSourceApiService GetWorkspaceSource", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var workspaceSourceName string

        resp, httpRes, err := apiClient.WorkspaceSourceApi.GetWorkspaceSource(context.Background(), workspaceSourceName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test WorkspaceSourceApiService ListWorkspaceSources", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.WorkspaceSourceApi.ListWorkspaceSources(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
