/*
Solar API

Testing CMSISIntellisenseBuildersApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_client_CMSISIntellisenseBuildersApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test CMSISIntellisenseBuildersApiService GetCmsisIntellisense", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var builderName string

        resp, httpRes, err := apiClient.CMSISIntellisenseBuildersApi.GetCmsisIntellisense(context.Background(), builderName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CMSISIntellisenseBuildersApiService ListCmsisIntellisense", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.CMSISIntellisenseBuildersApi.ListCmsisIntellisense(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CMSISIntellisenseBuildersApiService StartCmsisIntellisense", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var builderName string

        resp, httpRes, err := apiClient.CMSISIntellisenseBuildersApi.StartCmsisIntellisense(context.Background(), builderName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
